site_url: https://achkouyan.com
site_id: 358af28c-4867-4284-8027-0cc462e9d33f
backend:
  name: github
  repo: goldo/achkouyan.com # Path to your GitHub repository
media_folder: 'static/images' # Media files will be stored in the repo under static/images/uploads
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - name: 'about'
        label: 'About'
        file: 'content/about.md'
        fields: # The fields for each document, usually in front matter
          - { label: 'Body', name: 'body', widget: 'markdown' }
