---
label: Post
name: post
fields:
  - type: text
    label: Title
    name: title
  - type: text
    label: Excerpt
    name: excerpt
  - type: text
    label: Cover Image
    name: coverImage
  - type: text
    label: Date
    name: date
  - type: field_group
    label: Author
    name: author
    fields:
      - type: text
        label: Name
        name: name
      - type: text
        label: Picture
        name: picture
  - type: field_group
    label: OG Image
    name: ogImage
    fields:
      - type: text
        label: Url
        name: url
